### ISSUE TITLE
Update pixel maps to D110 geometry

### ISSUE THREAD

**Issue by VourMa** [SegmentLinking/cmssw#51]
With cms-sw/cmssw#45175, the default Phase 2 geometry has been moved to D110 = T35+C18+M11+I17+O9+F8.
T35 constitutes a significant change in the inner tracker geometry wrt. T32 that we were using before:
> - T35: Same as T33 with the exception of modified Tracker volume so that it touches CALO on the outer side and BeamPipe on the inner side
> - T33: Phase2 tilted tracker. Identical to T32 apart from a **more realistic description of the 3D sensors in TBPX layer1**.
> - T32: Phase2 tilted tracker. The tracker description is identical to T25. The outer radius of the tracker volume is reduced to avoid a clash with the BTL geometry (same as T31). The positions of the tracker components are not affected. This geometry is intended as a transition step towards a realistic configuration with 3D sensors in TBPX layer1.

As a result, I think that the pixel maps should be rederived for that geometry and tested, before we move to the new default.

**Comment by VourMa** [comment]
The conflict in cms-sw/cmssw#45117 comes from the transition to the new default geometry. Should I resolve the conflict by leaving our workflow in the previously default geometry (D98) and deal with the transition in an upcoming PR?

**Comment by slava77** [comment]
> The conflict in [cms-sw#45117](https://github.com/cms-sw/cmssw/pull/45117) comes from the transition to the new default geometry. Should I resolve the conflict by leaving our workflow in the previously default geometry (D98) and deal with the transition in an upcoming PR?

it would be more clear to discuss conflicts inline in #30

**Comment by slava77** [comment]
> The conflict in [cms-sw#45117](https://github.com/cms-sw/cmssw/pull/45117) comes from the transition to the new default geometry. Should I resolve the conflict by leaving our workflow in the previously default geometry (D98) and deal with the transition in an upcoming PR?

I'm not sure I follow: in our PR `umWFIB.extend([24834.703,24834.704]) #2026D98 ` is already D98

**Comment by slava77** [comment]
ah, OK, I see; the file was changed to a generic `[prefixDet+`
the only way that can work is if ±4 lines are identical

**Comment by ariostas** [comment]
Is T35 supposed to appear [here](https://cms-tklayout.web.cern.ch/cms-tklayout/layouts-work/cmssw-models/index.html) soon, or is it the same as T33? I was thinking of looking at this while also addressing https://github.com/SegmentLinking/TrackLooper/issues/329 since that was brought up in the review.

**Comment by VourMa** [comment]
> Is T35 supposed to appear [here](https://cms-tklayout.web.cern.ch/cms-tklayout/layouts-work/cmssw-models/index.html) soon, or is it the same as T33? I was thinking of looking at this while also addressing [SegmentLinking/TrackLooper#329](https://github.com/SegmentLinking/TrackLooper/issues/329) since that was brought up in the review.

Quoting the `Configuration/Geometry/README.md`:
> T35: Same as T33 with the exception of modified Tracker volume so that it touches CALO on the outer side and BeamPipe on the inner side.

I don't think this is a change in the actual layout, so T33 should be ok to look at at this level.

The problem is that  `D98 = T32+C17+M10+I16+O9+F8` and T32 -> T33 is a significant change for the IT.

**Comment by VourMa** [comment]
Could you remind me, did we agree that this is not an issue for us? @slava77 @ariostas @GNiendorf

**Comment by slava77** [comment]
> Could you remind me, did we agree that this is not an issue for us? @slava77 @ariostas @GNiendorf

I think that elsewhere we concluded that our map files by construction do not depend on IT geometry, only OT module positions/sizes matter.

**Comment by VourMa** [comment]
> I think that elsewhere we concluded that our map files by construction do not depend on IT geometry, only OT module positions/sizes matter.

Exactly, that's what I remember as well. I am closing this, thanks!
