### ISSUE TITLE
Consistency in the way we choose the `pixelType` and the way the pixel maps are constructed

### ISSUE THREAD

**Issue by VourMa** [SegmentLinking/cmssw#86]
In the code, we currently have a `FIXME` about the way we build the variable (`pixelSegmentDeltaPhiChange`) that determines the `pixelType`, which is used to determine which pixel map is to be used (` `, `pos`, or `neg`):

https://github.com/SegmentLinking/cmssw/blob/ff27cf3a74126ec211afe219415f242d7797228f/RecoTracker/LSTCore/src/alpaka/LST.dev.cc#L87-L97

Is this consistent with the way we build the pixel maps, i.e. is the same variable (even if not completely accurate) used or is something else used there?

I tried reading the code in SegmentLinking/LSTGeometry but things were not immediately clear to me. Maybe @GNiendorf, who did the refactoring of that code, could help when there is some spare time?

**Comment by GNiendorf** [comment]
https://github.com/SegmentLinking/LSTGeometry/blob/15f482747748e89632fbef65989355ddbb8d94d7/compute_pixelmap.py#L74-L161

https://github.com/SegmentLinking/LSTGeometry/blob/15f482747748e89632fbef65989355ddbb8d94d7/DetectorGeometry.py#L157-L167

Looks like a different definition? I don't have much time, but I think the relevant code is given by the links above.

**Comment by VourMa** [comment]
Looking at this, it seems to me like using different definitions doesn't matter, as they are used for different things: in the pixel map creation to define ranges of φ windows, while in the LST code the only thing that matters is whether curvature is positive or negative, without investigating specific φ ranges. If my understanding is correct, I think this is not a question of consistency but it boils down to "is the variable used to split to positive/negative charge good enough?" (independent of the pixel maps).

**Comment by slava77** [comment]
From my reading, `getCompatiblePhiRange` clearly uses charge/pt_range to figure out where compatible modules are for a given phi bin of the pLS (this is based on p3 at PCA). This is relevant for pLS with pt<2 GeV. 

The difference is the largest at the lowest pt and for 0.8 GeV will be around `2*26/173/0.8~0.38` (twice for the wrong charge) at OT L1 (around 26 cm)

But then in the code we use the sign of the pLS  last hit phi to assign.

Note though that in the standalone we are using deltaPhi https://github.com/SegmentLinking/TrackLooper/blob/cfbb863e5cb6b1d673a7acf9464f8f2f6c635eae/code/core/trkCore.cc#L696-L697, which should be correct.

**Comment by VourMa** [comment]
> Note though that in the standalone we are using deltaPhi https://github.com/SegmentLinking/TrackLooper/blob/cfbb863e5cb6b1d673a7acf9464f8f2f6c635eae/code/core/trkCore.cc#L696-L697, which should be mostly correct.

Do I understand correctly that the bug is not properly taking into account that φ circles back to 0(-π) when it crosses 2π(π)?

**Comment by slava77** [comment]
> > Note though that in the standalone we are using deltaPhi https://github.com/SegmentLinking/TrackLooper/blob/cfbb863e5cb6b1d673a7acf9464f8f2f6c635eae/code/core/trkCore.cc#L696-L697, which should be mostly correct.
> 
> Do I understand correctly that the bug is not properly taking into account that φ circles back to 0(-π) when it crosses 2π(π)?

do you mean why I said `mostly correct` about deltaPhi in trkCore? In that case "mostly" refers to the deltaPhi sign relationship working only for prompt tracks (displacement much smaller than the last hit position).

As for using `hit.phi` in LST.dev.cc , it's just plain wrong, it does not describe the charge of the pLS.

**Comment by VourMa** [comment]
I am trying to understand what I can quickly fix in #85. Based on our discussion, I will use the `deltaPhi` function, as in the standalone but keep the FIXME to be followed up separately.

**Comment by slava77** [comment]
> I am trying to understand what I can quickly fix in #85. Based on our discussion, I will use the `deltaPhi` function, as in the standalone but keep the FIXME to be followed up separately.

I think that switching to `deltaPhi` should be enough to already remove the FIXME or tone it down to "consider using charge directly" (but then add it both in LST and trkCore)

**Comment by slava77** [comment]
@VourMa 
should this be closed?

**Comment by VourMa** [comment]
Fixed in #85
