### ISSUE TITLE
NaN Values in rzChiSquared Variables

### ISSUE THREAD

**Issue by GNiendorf** [SegmentLinking/cmssw#95]
On an 1000 event sample from the PU200RelVal sample I noticed that there were some NaN values for the  t5_rzChiSquared and pt5_rzChiSquared variables in the output ntuple. @YonsiG or anyone else, is this expected?

**Comment by YonsiG** [comment]
Yes, I think it is known because if a track lays exactly on one line, we cannot build circles and calculate radius according to it, so the helix r-z chi2 returns NaN. There is some special treatment for the NaN tracks if pT>100. There could be still remaining tiny portion of tracks having NaN, but won't affect much I think. https://github.com/SegmentLinking/cmssw/blob/ff8446c8a375a0a535e627ad007d330950f49abb/RecoTracker/LSTCore/src/alpaka/Quintuplet.h#L607

**Comment by GNiendorf** [comment]
> Yes, I think it is known because if a track lays exactly on one line, we cannot build circles and calculate radius according to it, so the helix r-z chi2 returns NaN. There is some special treatment for the NaN tracks if pT>100. There could be still remaining tiny portion of tracks having NaN, but won't affect much I think.
> 
> https://github.com/SegmentLinking/cmssw/blob/ff8446c8a375a0a535e627ad007d330950f49abb/RecoTracker/LSTCore/src/alpaka/Quintuplet.h#L607

The code that you linked though is "or" though right, not "and"? So even if the inner_pt is under 100 but the rzChisquared is NaN then it would still trigger that if statement? So the NaN tracks must be dealt with somewhere else if some are getting through?

**Comment by GNiendorf** [comment]
I guess if it falls into one of these if statements afterwards then the track is not rejected? And that's probably how these NaN tracks are getting through?

https://github.com/SegmentLinking/cmssw/blob/ff8446c8a375a0a535e627ad007d330950f49abb/RecoTracker/LSTCore/src/alpaka/Quintuplet.h#L662-L666

**Comment by GNiendorf** [comment]
@slava77 Does it make sense to allow numbers to go NaN in our code and handle it through the is_nan check? Or should we always check before relevant division etc. that it won't produce nan?

**Comment by GNiendorf** [comment]
I just checked and there are no NaN's being passed to addQuintupletToMemory. It's only when the results are being read in write_lst_ntuple.cc that the NaN's show up, so something must be going wrong...:

https://github.com/SegmentLinking/cmssw/blob/ff8446c8a375a0a535e627ad007d330950f49abb/RecoTracker/LSTCore/standalone/code/core/write_lst_ntuple.cc#L487

**Comment by GNiendorf** [comment]
As a follow-up on the skype conversation, the reason this occurs is that when fast math is enabled the is_nan checks in Quintuplet.h are disabled, leading to NaN's in the output ntuple.
